# Generated by Django 6.0.3 on 2026-03-28 12:45

from django.db import migrations

def seed_data(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Product = apps.get_model('api', 'Product')

    electronics = Category.objects.create(name='Electronics')
    clothing = Category.objects.create(name='Clothing')

    Product.objects.create(
        name='iPhone 15',
        price=999.99,
        description='Apple smartphone',
        count=10,
        is_active=True,
        category=electronics
    )
    Product.objects.create(
        name='T-Shirt',
        price=19.99,
        description='Cotton t-shirt',
        count=50,
        is_active=True,
        category=clothing
    )

def unseed_data(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
